"""
Pydantic models for the Roadmap output.

Used with `.with_structured_output(Roadmap)` when calling Gemini Flash
in roadmap_generator.py. Frozen after Day 1 alongside NexusState.
"""

from typing import Literal, Optional
from pydantic import BaseModel, Field


class Resource(BaseModel):
    """A single learning resource attached to a level."""

    title: str = Field(..., description="Title of the resource")
    type: Literal["article", "video", "exercise", "project", "documentation"] = Field(
        ..., description="The kind of resource"
    )
    url: Optional[str] = Field(
        default=None, description="Link to the resource, if applicable"
    )
    description: Optional[str] = Field(
        default=None, description="Short description of what this resource covers"
    )


class Level(BaseModel):
    """A single level/stage within a roadmap."""

    index: int = Field(..., description="Zero-based order of this level in the roadmap")
    title: str = Field(..., description="Title of this level")
    description: str = Field(..., description="What the user will learn in this level")
    locked: bool = Field(
        default=True, description="Whether this level is locked until prior levels complete"
    )
    resources: list[Resource] = Field(
        default_factory=list, description="Learning resources for this level"
    )


class Roadmap(BaseModel):
    """The full personalised roadmap returned by the roadmap generator node."""

    skill_name: str = Field(..., description="The skill this roadmap covers")
    skill_level: Literal["beginner", "intermediate", "advanced"] = Field(
        ..., description="The user's skill level this roadmap targets"
    )
    total_levels: int = Field(..., description="Total number of levels in this roadmap")
    levels: list[Level] = Field(..., description="Ordered list of levels, at least 3")


class MiniLevel(BaseModel):
    """A single short lesson within an adaptive sublevel mini-roadmap."""

    index: int = Field(..., description="Zero-based order of this lesson")
    title: str = Field(..., description="Title of this mini-lesson")
    description: str = Field(..., description="What this mini-lesson covers")
    concept_tag: str = Field(..., description="The concept gap this lesson targets")


class MiniRoadmap(BaseModel):
    """A targeted remediation roadmap generated by the adaptive sublevel node."""

    title: str = Field(..., description="Title of the mini-roadmap")
    description: str = Field(..., description="Brief description of the remediation focus")
    target_concepts: list[str] = Field(
        ..., description="The concept gaps this mini-roadmap targets"
    )
    lessons: list[MiniLevel] = Field(
        ..., description="2-4 short lessons targeting the identified gaps, plus a re-test"
    )
